" set guifont to be same as terminal fonts
set guifont=Roboto\ Mono\ Light\ 9

" always use a block cursor
set guicursor=a:block

" set guioptions to the defaults, but with the following removed:
" menu bar, GUI tab bar, tool bar, scroll bars
set guioptions-=e
set guioptions-=g
set guioptions-=m
set guioptions-=r
set guioptions-=L
set guioptions-=t
set guioptions-=T
