""" VIM CONFIG {{{
""" MISC EDITOR BEHAVIOR {{{
" use matchit
packadd! matchit

" use Unicode
set encoding=utf-8

" make Vim detect filetypes and apply filetype plugin and indent files
filetype plugin indent on

" enable syntax highlighting
syntax enable

" allow Vim to hide modified buffers without abandoning them
set hidden

" delete comment characters when joining lines
set formatoptions+=j

" remove timeout on mappings but keep them for key codes
" to remove timeout from mapleader but avoid breaking <ESC> codes
set notimeout
set ttimeout
set ttimeoutlen=50

" make Vim use ripgrep for :grep
set grepprg=rg\ --vimgrep\ --no-heading

" change characters used to fill vsplit separator and folds
set fillchars=fold:\ ,diff:-

" display trailing whitespace and line continuations in list mode
set listchars=trail:_,extends:>,precedes:<,tab:>-

" disallow octal detection for <C-a>/<C-x>
set nrformats-=octal

" make Vim use vsplits for diff mode
set diffopt+=vertical
""" MISC EDITOR BEHAVIOR }}}

""" STATUSLINE BEHAVIOR {{{
" make Vim display the statusline at all times
" but the tabline only when necessary
set laststatus=2
set showtabline=1

" define statusline items
set statusline=
" filename
set statusline+=%*
set statusline+=%(%{statusline#bufnameshort()}%)
" window type (help, preview, qlist)
set statusline+=%*
set statusline+=%(%h%w%)
" modified flag
set statusline+=%3*
set statusline+=%(%m%)
" readonly flag
set statusline+=%1*
set statusline+=%(%r%)
" midline separator
set statusline+=%=
" quickfix flag
set statusline+=%3*
set statusline+=%(%{statusline#quickfix()}%)
""" END STATUSLINE BEHAVIOR }}}

""" WINDOW BEHAVIOR {{{
" make Vim add new vertical splits to the right
" and new horizontal splits below
set splitright
set splitbelow
""" END WINDOW BEHAVIOR }}}

""" TEMP FILES BEHAVIOR {{{
" make Vim save swapfiles, backups, and undofiles in .vim
" so I can make use of them without cluttering the working directory
set swapfile
set backup
set undofile
set directory=~/.vim/tmp//,.
set backupdir=~/.vim/tmp//,.
set undodir=~/.vim/tmp//,.
""" END TEMP FILES BEHAVIOR }}}

""" COLORS {{{
" set the colorscheme
colorscheme highlight
""" END COLORS }}}

""" INDENT BEHAVIOR {{{
" set up indents to use 2 spaces
set shiftwidth=2

" set up <Tab> to insert an indent instead of a tab character
" this relies on the value of shiftwidth
set softtabstop=-1
set expandtab

" make <Tab> insert an indent (shiftwidth) when at the start of a line
" and a tab character elsewhere (tabstop/softtabstop)
" my softabstop is set up to rely on shiftwidth so this may seem superfluous
" but there may be times I'd want to change tab settings locally
set smarttab

" make tab characters display as 8 characters wide
set tabstop=8

" make Vim auto indent when typing new lines
set autoindent
""" END INDENT BEHAVIOR }}}

""" SEARCH BEHAVIOR {{{
" allow incremental search
set incsearch

" highlight search results
set hlsearch

" make search case sensitive for queries with capital letters
" but case insensitive for everything else
set ignorecase
set smartcase
""" END SEARCH BEHAVIOR }}}

""" COMPLETION BEHAVIOR {{{
" disallow preview during completion
set completeopt&
set completeopt-=preview
""" END COMPLETION BEHAVIOR }}}

""" BUFFER-SPECIFIC BEHAVIOR {{{
augroup BufferSpecific
  autocmd!

  " disallow soft-wrapping in quickfix and loc lists
  autocmd FileType qf setlocal nowrap

  " automatically set cursorline for todo.txt, and quickfix
  autocmd FileType gitcommit,todo,qf setlocal cursorline

  " set notes textwidth to 80
  autocmd FileType vimwiki,markdown setlocal textwidth=80

  " set spell check for prose-related buffers
  autocmd FileType vimwiki,markdown,gitcommit setlocal spell

  " set makeprg to pandoc for markdown
  autocmd FileType markdown setlocal makeprg=pandoc\ %\ -o\ %:r.pdf
augroup END
""" END BUFFER-SPECIFIC BEHAVIOR }}}

""" COMMAND LINE BEHAVIOR {{{
" display commands below the statusline
set showcmd

" display tab completions for command line
set wildmenu

" partial-complete before displaying wildmenu, then cycle through options
set wildmode=list:full,full

" ignore case when completing files
set wildignorecase

" limit command history
set history=100

" abbreviate commandline messages as much as possible
" to help avoid hit-enter prompts
set shortmess=atoO

" map keys to expand my own system of snippets
" add both <C-Space><C-Space> and <C-Space><C-Space>, to cover errors
cmap <C-@><Space> <Plug>SnipletExpand
cmap <C-@><C-@> <Plug>SnipletExpand

" make Vim use history recall even for <C-n>/<C-p>
" since they're easier to hit than the arrow keys
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
""" END COMMAND LINE BEHAVIOR }}}

""" TERMINAL MODE BEHAVIOR {{{
" map a key to quickly quit the terminal buffer, disregarding the running job
tnoremap <C-w>q <C-w>:bd!<CR>
""" END TERMINAL MODE BEHAVIOR }}}

""" NORMAL MODE BEHAVIOR {{{
" map a key to quickly close a tab
nnoremap ZT :tabclose<CR>

" map Y to y$, to be similar to D and C
nnoremap Y y$

" map <BS> to switch to the alternate buffer
nnoremap <BS> <C-^>
""" END NORMAL MODE BEHAVIOR }}}

""" INSERT MODE BEHAVIOR {{{
" allow <BS> to delete the following special characters
set backspace=indent,eol,start

" map <C-@> to nop, so I can use it as my Insert mode leader
" this byte is sent by both <C-2> and <C-Space>
inoremap <C-@> <nop>

" map keys to expand my own system of snippets
" add both <C-Space><C-Space> and <C-Space><C-Space>, to cover errors
imap <C-@><Space> <Plug>SnipletExpand
imap <C-@><C-@> <Plug>SnipletExpand

" map keys to quickly insert dates and times
inoremap <C-@>d <C-r>=strftime('%F')<CR>
inoremap <C-@>t <C-r>=strftime('%R')<CR>
inoremap <C-@>i <C-r>=strftime('%FT%T%z')<CR>
""" END INSERT MODE BEHAVIOR }}}

""" VISUAL MODE BEHAVIOR {{{
" make the <> indent commands preserve the highlighted visual block
xnoremap > >gv
xnoremap < <gv
""" END VISUAL MODE BEHAVIOR }}}

""" NON-MODE-SPECIFIC MAPS {{{
" unmap <Space> so it doesn't move to the right when I press <Leader>
" since I have <Space> as <Leader>
nnoremap <Space> <nop>
xnoremap <Space> <nop>

" swap g] and g<C-]>
" since g<C-]> jumps immediately if there is just one tag, which I want
" but g] is easier to press
noremap g] g<C-]>
noremap g<C-]> g]
noremap <C-w>g] <C-w>g<C-]>
noremap <C-w>g<C-]> <C-w>g]

" map keys for changing with cgn
nnoremap <silent> gz :set operatorfunc=visual_op#maps#Cgn<CR>g@
xmap gz <Plug>SearchInPlacecgn
""" END NON-MODE-SPECIFIC MAPS }}}

""" COMMANDS {{{
" define a command for splitting a statement with a ternary operator
command! -nargs=0 SplitTernary
  \ silent execute
  \ "normal! 0f?i\<CR>\<Esc>f:i\<CR>\<Esc>Vkk:keeppatterns s/\s\+$//e\<CR>"
command! -nargs=0 SplitWrapperXML
  \ silent execute "normal! ^f>a\<CR>\<Esc>$F<i\<CR>\<Esc>"

" define commands to post to pastebins
command! -nargs=0 -range Sprunge
  \ <line1>,<line2>w ! curl -F "sprunge=<-" http://sprunge.us
command! -nargs=0 -range Ixio
  \ <line1>,<line2>w ! curl -F "f:1=<-" ix.io

" define wrapper commands to set makeprg
command! -nargs=+ MakePrg let &makeprg=<q-args>

" define commands to run native functions with AsyncRun
command! -bang -nargs=* -complete=file Make AsyncRun -program=make @ <args>
command! -bang -nargs=+ Grep AsyncRun -program=grep @ <args>
""" END COMMANDS }}}

""" LEADER KEY BEHAVIOR {{{
" change Leader key to Spacebar, since \ is too hard to reach
let mapleader = "\<Space>"

" map a key to reset search text
nnoremap <Leader><Leader> :nohlsearch<CR>

" map keys for Fugitive
nnoremap <Leader>gs :tab split \| Gstatus \| wincmd o<CR>
nnoremap <Leader>ga :Gwrite<CR>
nnoremap <Leader>gc :Gcommit --verbose<CR>
nnoremap <Leader>gm :Gmerge<CR>
nnoremap <Leader>gb :Gina blame<CR>
nnoremap <Leader>gl :Gllog -- %<CR><CR><CR>
nnoremap <Leader>gL :Gllog<CR><CR><CR>

" map keys for FZF
nnoremap <Leader>fp :Files<CR>
nnoremap <Leader>fb :Buffers<CR>
nnoremap <Leader>fl :BLines<CR>

" map keys for useful native Vim functions
nnoremap <Leader>vv :source $MYVIMRC<CR>
nnoremap <Leader>vp :packadd<Space>
" edit with no parameters is useful for reloading a buffer
nnoremap <Leader>vr :edit<CR>
nnoremap <Leader>vff :filetype detect<CR>
nnoremap <Leader>vft :set filetype=
nnoremap <Leader>vt :vert term<Space>
nnoremap <Leader>vdd :setlocal foldmethod=
nnoremap <Leader>vds :setlocal foldmethod=syntax<CR>
nnoremap <Leader>vdk :setlocal foldmethod=marker<CR>
nnoremap <Leader>vdm :setlocal foldmethod=manual<CR>

" map keys for quick-buffer
nnoremap <Leader>b :B<Space>

" map keys for quickfix and loc lists
nmap <Leader>qq <Plug>qf_qf_toggle
nmap <Leader>ql <Plug>qf_loc_toggle

" map keys for search
nmap <Leader>h <Plug>SearchInPlace
xmap <Leader>h <Plug>SearchInPlace
nmap <Leader>G <Plug>GrepStar
xmap <Leader>G <Plug>GrepStar

" map a key to trigger ArgWrap
nnoremap <Leader>a :ArgWrap<CR>

" map keys for AsyncRun
nnoremap <Leader>rr :AsyncRun<Space>
nnoremap <Leader>rm :Make<Space>
nnoremap <Leader>rg :Grep<Space>

" map keys for Makery.vim
nnoremap <Leader>ml :Mlint %<CR>
nnoremap <Leader>mg :Mtags<CR>
nnoremap <Leader>mt :Mtest<CR>
nnoremap <Leader>mb :Mbuild<CR>

" map keys for Vim-Slime
xmap <Leader>s <Plug>SlimeRegionSend
nmap <Leader>s <Plug>SlimeMotionSend
nmap <Leader>ss <Plug>SlimeLineSend
""" END LEADER KEY BEHAVIOR }}}
""" END VIM CONFIG }}}

""" PLUGIN CONFIG {{{
""" NETRW {{{
" disallow Netrw from setting the alternate buffer
" to ensure that <C-^> always lands on a file buffer not a dir
let g:netrw_altfile = 1

" disallow Netrw from displaying its banner
let g:netrw_banner = 0
""" END NETRW }}}

""" COMPLETOR.VIM {{{
" disallow auto popup except for filename
" auto popup needs certain completeopt settings to work sanely
" but that messes with repeated <C-x><C-p> and <C-l> completion
let g:completor_disable_filename = 0
let g:completor_disable_buffer = 1
let g:completor_disable_ultisnips = 1

augroup Completor
  autocmd!

  " completor.vim automatically sets up completeopt
  " such that it works sanely with auto popup (noselect in particular)
  " set it back after completion
  autocmd CompleteDone * set completeopt& | set completeopt-=preview
augroup END
""" END COMPLETOR.VIM }}}

""" VIM-QF {{{
" disallow Vim-QF from automatically resizing quickfix and location windows
let g:qf_auto_resize = 0

" disallow Vim-QF from automatically opening quickfix and location windows
let g:qf_auto_open_quickfix = 0
let g:qf_auto_open_loclist = 0

" make :Keep and friends match buffer name only
let g:qf_bufname_or_text = 1
""" END VIM-QF }}}

""" VIM-KICKFIX {{{
" tweak zebra colors for quickfix window
highlight qfFileName1 ctermfg=4
highlight qfFileName2 ctermfg=6
highlight link qfZebra1 Normal
highlight link qfZebra2 Normal
""" END VIM-KICKFIX }}}

""" VIMWIKI {{{
" allow VimWiki to fold sections and code blocks
let g:vimwiki_folding = 'expr'
""" END VIMWIKI }}}

""" VIM-ARGWRAP {{{
" make ArgWrap add tail commas when working with [] or {}
let g:argwrap_tail_comma_braces = '[{'
""" END VIM-ARGWRAP }}}

""" EMMET.VIM {{{
" make Emmet.vim set only <Plug> mappings
" since I only ever use the expand and the next/prev mappings
let g:emmet_install_only_plug = 1
""" END EMMET.VIM }}}

""" AUTO-PAIRS {{{
" disallow AutoPairs from jumping to closing brackets on the next line
let g:AutoPairsMultilineClose = 0

" disable certain pairs when in Lisp files, especially quote (')
augroup AutoPairs
  autocmd!
  autocmd FileType lisp let b:AutoPairs = {'(': ')', '"': '"'}
augroup END
""" END AUTO-PAIRS }}}

""" VIM-TMUX-NAVIGATOR {{{
" disallow tmux-navigator's default navigation keys
" I set my own keys in after/plugin/tmux_navigator.vim
let g:tmux_navigator_no_mappings = 1
""" END VIM-TMUX-NAVIGATOR }}}

""" VIM-SLIME {{{
" make vim-slime work with tmux panes by default
" guard for tmux
if $TMUX != ""
  let g:slime_target = "tmux"
  let g:slime_default_config = {"socket_name": split($TMUX, ",")[0], "target_pane": ":.1"}
endif

" unset vim-slime's default emacs bindings
" My own maps are in the VIM CONFIG section, under LEADER KEY BEHAVIOR
let g:slime_no_mappings = 1
""" END VIM-SLIME }}}

""" VIM-TABLE-MODE {{{
" make tables bitbucket-markdown-compatible
let g:table_mode_corner = '|'
let g:table_mode_corner_corner = '|'
let g:table_mode_header_fillchar = '-'

" disallow vim-table-mode from automatically aligning every now and then
let g:table_mode_auto_align = 0
""" END VIM-TABLE-MODE }}}

""" VIM-JSON {{{
" define a default highlight for vim-JSON's highlight groups
highlight default link jsObjectKey Label
""" END VIM-JSON }}}

""" VIM-JSX {{{
" allow Vim-JSX to work even without a .jsx extension
let g:jsx_ext_required = 0
""" END VIM-JSX }}}

""" VIM-VUE {{{
" disallow vim-vue from doing multiple regex checks for pre-processors
" for performance
let g:vue_disable_pre_processors = 1
""" END VIM-VUE }}}

""" VIM-TEMPLATE-LITE {{{
" declare mappings of patterns to templates to load
let g:template_lite_mappings = {
  \  '*.component.js': 'react-native/component.js',
  \  '*.hoc.js': 'react-native/hoc.js',
  \  '*.container.js': 'react-native/container.js',
  \  '*.styles.js': 'react-native/styles.js',
  \  '*.redux.js': 'react-native/redux.js',
  \  '*.fire.js': 'react-native/fire.js',
  \  '*.component.jsx': 'react/component.jsx',
  \  '*.hoc.jsx': 'react/hoc.jsx',
  \  '*.component.ts': 'angular/component.ts',
  \  '*.vue': 'vue/component.vue',
  \  '*.sh': 'sh.sh',
  \}

" trigger vim-abolish on template load
augroup TemplatesVim
  autocmd!

  " replace skeleton-name with filename
  autocmd User TemplateLoad silent! execute
    \ "%S/skeleton-name/" . path#remove_extension(expand('%:t')) . "/g"
augroup END
""" END VIM-TEMPLATE-LITE }}}
""" END PLUGIN CONFIG }}}

" vim:fdm=marker
