#!/usr/bin/env bash

die () {
	printf '%s\n' "$*" >&2
	exit 1
}

# vimrc -> init.vim
mkdir -p ~/.config/nvim || die 'Cannot create ~/.config/nvim. Aborting.'
ln -sf ~/.vim/vimrc ~/.config/nvim/init.vim
